php:
  container_name: php
  build: ./php-fpm
  links:
    - db
  volumes:
    - ./code:/var/www/html/
    - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    - ./php-fpm/newrelic.ini:/usr/local/etc/php/conf.d/newrelic.ini:ro
  expose:
    - "9000"
  restart: always

nginx:
  container_name: nginx
  image: nginx:latest
  links:
    - php
  volumes:
    - ./code:/var/www/html/
    - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "80"
  restart: always

db:
  container_name: db
  image: mysql:5.7
  volumes:
    - ./db/data/:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  expose:
      - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
  restart: always
